services:
  - type: web
    name: resumeparse-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: ./run.sh
    autoDeploy: true
    envVars:
      - key: APP_ENV
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_MONTHLY
        sync: false
      - key: STRIPE_PRODUCT_ID
        sync: false
      - key: DEFAULT_MONTHLY_QUOTA
        sync: false
